version: "3"

services:
  
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file: ./.env
    ports:
      - $CLIENT_LOCAL_PORT:$CLIENT_DOCKER_PORT
    container_name: mevn-client
    networks:
      - mevn-stack-net
    volumes:
      - ./client/src:/usr/app/src
      - ./client/public:/usr/app/public
    depends_on:
      - server
    stdin_open: true
    tty: true

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=db
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    stdin_open: true
    tty: true
    container_name: mevn-server
    networks:
      - mevn-stack-net
    volumes:
      - ./server/src:/usr/app/src
    depends_on:
      - db

  db:
    image: mongo
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_DATABASE=$MONGODB_DATABASE
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    container_name: mongo-db
    networks:
      - mevn-stack-net
    volumes:
      - ./server/mongo-data:/data/db

networks:
  mevn-stack-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local